-- APPROVAL 판정과 승인 요청(docs/06 §11). 감사 행은 COMPLETED + APPROVAL로 한 번 확정되고,
-- 승인 여부는 감사 행이 아니라 승인 요청이 가진다.

alter table audit_events drop constraint audit_events_decision_check;
alter table audit_events
    add constraint audit_events_decision_check check (decision in ('ALLOW', 'BLOCK', 'APPROVAL'));

-- 감사 행 하나에 승인 요청은 최대 하나다(unique). 무엇을 요청했는지는 감사 행에서 복사해 둔다.
create table approval_requests (
    approval_request_id varchar(64)              not null,
    audit_event_id      varchar(64)              not null,
    agent_id            varchar(64)              not null,
    agent_run_id        varchar(64)              not null,
    case_id             varchar(64),
    target_consumer_id  varchar(64),
    requested_tool      varchar(64),
    status              varchar(32)              not null,
    created_at          timestamp(6) with time zone not null,
    version             bigint                   not null,
    primary key (approval_request_id),
    constraint uk_approval_request_audit_event unique (audit_event_id),
    constraint fk_approval_request_audit_event foreign key (audit_event_id) references audit_events,
    -- 지금은 대기만 있다. 승인·거절·만료는 다음 단계에서 이 제약을 넓힌다.
    constraint chk_approval_request_status check (status in ('PENDING'))
);

create table approval_request_reason_codes (
    approval_request_id varchar(64) not null,
    reason_code         varchar(64) not null,
    primary key (approval_request_id, reason_code),
    constraint fk_approval_reason_codes_request foreign key (approval_request_id) references approval_requests
);

-- 승인 요청에 일어난 일. 쌓이기만 한다. 순서는 시각이 아니라 sequence로 정한다.
create table approval_request_events (
    approval_request_event_id bigint generated by default as identity,
    approval_request_id       varchar(64)              not null,
    sequence                  integer                  not null,
    event_type                varchar(32)              not null,
    occurred_at               timestamp(6) with time zone not null,
    actor_type                varchar(32)              not null,
    actor_id                  varchar(64),
    primary key (approval_request_event_id),
    constraint uk_approval_request_event_sequence unique (approval_request_id, sequence),
    constraint fk_approval_request_events_request foreign key (approval_request_id) references approval_requests,
    constraint chk_approval_request_event_sequence check (sequence >= 1),
    constraint chk_approval_request_event_type check (event_type in ('REQUESTED')),
    constraint chk_approval_request_event_actor_type check (actor_type in ('SYSTEM', 'EMPLOYEE')),
    -- 사람이 한 일에는 누가 했는지가 있어야 하고, 시스템이 한 일에는 없다.
    constraint chk_approval_request_event_actor check ((actor_type = 'EMPLOYEE') = (actor_id is not null))
);

-- 이벤트는 고치거나 지우지 않는다. 애플리케이션 버그나 수동 조작이 이력을 바꾸지 못하게 DB가 막는다.
-- TRUNCATE는 행 단위 트리거가 걸리지 않는다 — 관리 작업(테스트 정리 포함)으로만 쓴다.
create function reject_approval_request_event_change() returns trigger
    language plpgsql as $$
begin
    raise exception 'approval_request_events is append-only';
end;
$$;

create trigger trg_approval_request_events_append_only
    before update or delete on approval_request_events
    for each row execute function reject_approval_request_event_change();
