package io.finguard.core.domain;

/** 서비스 간 계약에서 허용하는 고정 Reason Code 어휘. {@code docs/06} §20. */
public enum ReasonCode {
    INVALID_TOOL_REQUEST,
    AGENT_AUTHENTICATION_FAILED,
    AGENT_IDENTITY_MISMATCH,
    DUPLICATE_REQUEST,
    REQUEST_RATE_LIMITED,
    CONTEXT_SERVICE_UNAVAILABLE,
    BEHAVIOR_HISTORY_UNAVAILABLE,
    CONTEXT_NOT_FOUND,
    EMPLOYEE_AUTHORITY_INACTIVE,
    EMPLOYEE_AUTHORITY_VIOLATION,
    PERMISSION_TEMPLATE_INACTIVE,
    PERMISSION_TEMPLATE_VIOLATION,
    CASE_INACTIVE,
    CASE_EXPIRED,
    CASE_SCOPE_VIOLATION,
    MANDATE_NOT_FOUND,
    MANDATE_INACTIVE,
    MANDATE_SCOPE_VIOLATION,
    TASK_PASSPORT_NOT_FOUND,
    TASK_PASSPORT_INACTIVE,
    TASK_PASSPORT_EXPIRED,
    TASK_PASSPORT_STALE,
    TOOL_SCOPE_VIOLATION,
    DATA_SCOPE_VIOLATION,
    PROMPT_INJECTION,
    BEHAVIOR_ANOMALY,
    HARD_REQUEST_LIMIT_EXCEEDED,
    PROMPT_RISK_UNAVAILABLE,
    BEHAVIOR_RISK_UNAVAILABLE,
    POLICY_ENGINE_UNAVAILABLE,
    POLICY_DECISION_INVALID,
    AUDIT_WRITE_FAILED,
    /** Core가 붙이는 코드다. 결과 기록이 도착하지 않은 시도가 있는 실행에 표시한다 — docs/04 §3. */
    AUDIT_OUTCOME_UNKNOWN,
    /** Core가 붙이는 코드다. 승인을 기다리는 시도가 있는 실행에 표시한다 — docs/04 §3. */
    AUDIT_APPROVAL_PENDING,
    /** Core가 붙이는 코드다. 승인 요청이 거절된 시도가 있는 실행에 표시한다. */
    AUDIT_APPROVAL_REJECTED,
    /** Core가 붙이는 코드다. 승인 요청이 처리되지 않거나 쓰이지 않은 채 만료된 실행에 표시한다. */
    AUDIT_APPROVAL_EXPIRED,
    /** 요청한 직원이 자기 승인 요청을 승인·거절하려 했다. */
    APPROVAL_SELF_DECISION,
    /** 이미 처리됐거나 기한이 지난 승인 요청이다. */
    APPROVAL_NOT_PENDING,
    /** 다시 실행에 지정한 승인을 이 요청에 쓸 수 없다. */
    APPROVAL_NOT_APPLICABLE,
    SECURITY_EVENT_WRITE_FAILED,
    DOWNSTREAM_ERROR,
    DOWNSTREAM_TIMEOUT,
    INTERNAL_CREDENTIAL_INVALID,
    CORE_API_CREDENTIAL_INVALID,
    CORE_API_ROLE_FORBIDDEN,
    EMPLOYEE_IDENTITY_MISMATCH,
    // 응답 단계(docs/04 §19). 앞의 셋은 MASK, 넷째는 호출 후 BLOCK, 나머지는 응답을 내보내지 않은 ERROR다.
    RRN_MASKED,
    ACCOUNT_NUMBER_MASKED,
    PHONE_NUMBER_MASKED,
    OTHER_CUSTOMER_DATA_IN_RESPONSE,
    RESPONSE_SCAN_UNAVAILABLE,
    RESPONSE_SCAN_DISABLED,
    RESPONSE_TOO_LARGE,
    MASKING_FAILED,
}
